=== jfedjaev/P300-DrinkMachine/PresetFiles/channelpresets-schema.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.biopac.com/ChannelPresets"
	xmlns="http://www.biopac.com/ChannelPresets" elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="1.0">
	<!-- ADD ANNOTATIONS IN ALL TYPES LATER -->
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Channel Presets Schema
			Copyright 2008 BIOPAC Systems, Inc.
		</xsd:documentation>
	</xsd:annotation>
	<!-- GROUPS FOR THE XML FORMAT -->
	<xsd:group name="DefinedPresetCollectionTypes">
		<xsd:sequence>
			<xsd:element name="analogpresetcollection" type="AnalogPresetCollectionType" />
			<xsd:element name="calcpresetcollection" type="CalcPresetCollectionType" />
		</xsd:sequence>
	</xsd:group>
	<!--CLASS TYPES FOR CHANNEL PRESETS XML FORMAT -->
	<!-- Channel Preset Collection Type -->
	<xsd:complexType name="ChannelPresetCollectionType">
		<xsd:sequence>
			<xsd:group ref="DefinedPresetCollectionTypes" />
			<xsd:any minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="version" type="MajorMinorVersionType" use="required" />
		<xsd:attribute name="creator" type="xsd:string" use="optional" />
		<xsd:anyAttribute />
	</xsd:complexType>
	<!-- End Channel Preset Collection Type -->
	<!-- Analog Channel Preset Collection Type -->
	<xsd:complexType name="AnalogPresetCollectionType">
		<xsd:sequence>
			<xsd:element name="analogpreset" type="AnalogPresetType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:anyAttribute />
	</xsd:complexType>
	<!-- End Analog Channel  Preset Collection Type -->
	<!-- Calculation Channel Preset Collection Type -->
	<xsd:complexType name="CalcPresetCollectionType">
		<xsd:sequence>
			<xsd:element name="calcpreset" type="CalcPresetType" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:anyAttribute />
	</xsd:complexType>
	<!-- End Analog Channel  Preset Collection Type -->
	<!-- (BASE) Channel Preset Type -->
	<xsd:complexType name="ChannelPresetType">
		<xsd:sequence>
			<xsd:element name="presetlabel" type="xsd:string" />
			<xsd:element name="channellabel" type="xsd:string" />
			<xsd:element name="unitslabel" type="xsd:string" />
			<xsd:element name="scaling" type="ScalingType" />
		</xsd:sequence>
		<xsd:attribute name="uid" type="xsd:ID" />
	</xsd:complexType>
	<!-- End (BASE) Channel Preset Type -->
	<!-- Analog Preset Type (extends Channel Preset Type) -->
	<xsd:complexType name="AnalogPresetType">
		<xsd:complexContent>
			<xsd:extension base="ChannelPresetType">
				<xsd:sequence>
					<!-- unbounded for future hardware configuration -->
					<xsd:element name="hardwareconfig" type="HardwareConfigType" minOccurs="0" maxOccurs="unbounded" />
					<!-- HOW DO YOU MAKE THIS EXTENSIBLE????? -->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!-- End Analog Preset Type (extends Channel Preset Type) -->
	<!-- Analog Preset Type (extends Channel Preset Type) -->
	<xsd:complexType name="CalcPresetType">
		<xsd:complexContent>
			<xsd:extension base="ChannelPresetType">
				<xsd:sequence>
					<xsd:any minOccurs="0" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!-- End Analog Preset Type (extends Channel Preset Type) -->
	<!-- Scaling Type -->
	<xsd:complexType name="ScalingType">
		<xsd:sequence>
			<!-- sequence of 2 or more value for non linear scaling or multisegment linear scaling -->
			<xsd:element name="value" type="ScalingValueType" minOccurs="2" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:anyAttribute />
	</xsd:complexType>
	<!-- End Scaling Type -->
	<!-- Hardware Configuration Type -->
	<xsd:complexType name="HardwareConfigType">
		<xsd:sequence>
			<xsd:element name="settings" type="HardwareSettingsType" />
			<xsd:element name="dspfiltercollection" type="DSPFilterCollectionType" />
			<xsd:any minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:integer" use="required" />
		<xsd:anyAttribute />
	</xsd:complexType>
	<!-- End Hardware Configuration Type -->
	<!-- Hardware Settings Type -->
	<xsd:complexType name="HardwareSettingsType">
		<xsd:sequence>
			<xsd:element name="gain" type="xsd:double" />
			<xsd:element name="offset" type="xsd:double" />
			<xsd:element name="inputcoupling" type="InputCouplingType" />
			<xsd:element name="highpassfilter" type="xsd:double" />
			<xsd:element name="lowpassfilter" type="xsd:double" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- End Hardware Settings Type -->
	<!-- DSP Filter Collection Type -->
	<xsd:complexType name="DSPFilterCollectionType">
		<xsd:sequence>
			<xsd:element name="dspfilter" type="DSPFilterType" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- End DSP Filter Collection Type -->
	<!-- DSP Filter Type -->
	<xsd:complexType name="DSPFilterType">
		<xsd:sequence>
			<xsd:element name="frequency" type="xsd:double" />
			<xsd:element name="q" type="xsd:double" />
		</xsd:sequence>
		<xsd:attribute name="type" type="FilterType" />
		<xsd:anyAttribute />
	</xsd:complexType>
	<!-- End DSP Filter Type -->
	<!-- Scaling Value Type -->
	<xsd:complexType name="ScalingValueType">
		<xsd:attribute name="unscaled" use="required" />
		<xsd:attribute name="scaled" use="required" />
		<xsd:anyAttribute />
	</xsd:complexType>
	<!-- End Scaling Value Type -->
	<!-- Filter Type -->
	<xsd:simpleType name="FilterType">
		<xsd:restriction base="xsd:string">
			<!-- Should we restrict it here because there might be filters we haven't defined yet -->
			<xsd:pattern value="None|LowPass|HighPass|BandPass|BandStop|BandStopLineFrequency" />
		</xsd:restriction>
	</xsd:simpleType>
	<!-- End Filter Type -->
	<!-- Input Coupling Type -->
	<xsd:simpleType name="InputCouplingType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="AC|DC" />
		</xsd:restriction>
	</xsd:simpleType>
	<!-- End Input Coupling Type -->
	<!-- Major Minor Version Type -->
	<xsd:simpleType name="MajorMinorVersionType">
		<xsd:restriction base="xsd:string">
			<!-- Restrict patterm for major.minor version numbering -->
			<xsd:pattern value="[0-9]+\.[0-9]+" />
		</xsd:restriction>
	</xsd:simpleType>
	<!-- End Major Minor Versin Type -->
	<!-- ELEMENTS FOR THE CHANNEL PRESET XML FORMAT -->
	<!-- Root Element Declaration -->
	<xsd:element name="channelpresetcollection" type="ChannelPresetCollectionType" />
	<!-- End Root Element Declaration -->
</xsd:schema>

=== jfedjaev/P300-DrinkMachine/MMN-P300/PresetFiles/channelpresets2.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="channelpresets-stylesheet.xsl"?>
<channelpresetcollection xmlns="http://www.biopac.com/ChannelPresets" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.biopac.com/ChannelPresets channelpresets-schema.xsd" version="1.0" creator="PresetXMLEditor">
	<analogpresetcollection>
		<analogpreset uid="a1">
			<presetlabel>Accelerometer (5 g's max.)</presetlabel>
			<channellabel>Accelerometer</channellabel>
			<unitslabel>g's</unitslabel>
			<scaling>
				<value unscaled="0.011000000000000" scaled="1.000000000000000" />
				<value unscaled="0.010000000000000" scaled="0.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>500</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="LowPass">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="LowPass">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="BandStopLineFrequency">
						<frequency>60.0000</frequency>
						<q>1.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a2">
			<presetlabel>Accelerometer (50 g's max.)</presetlabel>
			<channellabel>Accelerometer</channellabel>
			<unitslabel>g's</unitslabel>
			<scaling>
				<value unscaled="0.007500000000000" scaled="10.000000000000000" />
				<value unscaled="0.006500000000000" scaled="0.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>500</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="LowPass">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="LowPass">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="BandStopLineFrequency">
						<frequency>60.0000</frequency>
						<q>1.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a3">
			<presetlabel>Airflow (SS11LA)</presetlabel>
			<channellabel>Airflow</channellabel>
			<unitslabel>liters/sec</unitslabel>
			<scaling>
				<value unscaled="-0.003000000000000" scaled="-10.000000000000000" />
				<value unscaled="0.003000000000000" scaled="10.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>5000</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="LowPass">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="LowPass">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="BandStopLineFrequency">
						<frequency>60.0000</frequency>
						<q>1.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a4">
			<presetlabel>Airflow (SS52L)</presetlabel>
			<channellabel>Airflow</channellabel>
			<unitslabel>liters/sec</unitslabel>
			<scaling>
				<value unscaled="0.000000000000000" scaled="0.000000000000000" />
				<value unscaled="0.192500000000000" scaled="1.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>1000</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="LowPass">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="LowPass">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="BandStopLineFrequency">
						<frequency>60.0000</frequency>
						<q>1.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a5">
			<presetlabel>Blood Pressure Cuff</presetlabel>
			<channellabel>Blood Pressure Cuff</channellabel>
			<unitslabel>mmHg</unitslabel>
			<scaling>
				<value unscaled="0.000000000000000" scaled="0.000000000000000" />
				<value unscaled="0.002500000000000" scaled="100.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>500</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="LowPass">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="LowPass">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="BandStopLineFrequency">
						<frequency>60.0000</frequency>
						<q>1.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a6">
			<presetlabel>BNC (SS9L, -10 to +10 Volts max.)</presetlabel>
			<channellabel>BNC</channellabel>
			<unitslabel>Volts</unitslabel>
			<scaling>
				<value unscaled="-0.001000000000000" scaled="-1.000000000000000" />
				<value unscaled="0.001000000000000" scaled="1.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>1000</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="None">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="None">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="None">
						<frequency>60.0000</frequency>
						<q>5.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a7">
			<presetlabel>BNC (SS9L, -50 to +50 Volts max.)</presetlabel>
			<channellabel>BNC</channellabel>
			<unitslabel>Volts</unitslabel>
			<scaling>
				<value unscaled="-0.001000000000000" scaled="-1.000000000000000" />
				<value unscaled="0.001000000000000" scaled="1.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>200</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="None">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="None">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="None">
						<frequency>60.0000</frequency>
						<q>5.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a8">
			<presetlabel>BNC (SS70L, -10 to +10 Volts max.)</presetlabel>
			<channellabel>BNC</channellabel>
			<unitslabel>Volts</unitslabel>
			<scaling>
				<value unscaled="-1.000000000000000" scaled="-10.000000000000000" />
				<value unscaled="1.000000000000000" scaled="10.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>10</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.05</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="None">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="None">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="None">
						<frequency>60.0000</frequency>
						<q>5.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a9">
			<presetlabel>Cardiac Output - Z</presetlabel>
			<channellabel>Cardiac Output - Z</channellabel>
			<unitslabel>Ohms</unitslabel>
			<scaling>
				<value unscaled="0.000000000000000" scaled="0.000000000000000" />
				<value unscaled="0.050000000000000" scaled="100.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>200</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.5</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="LowPass">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="LowPass">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="BandStopLineFrequency">
						<frequency>60.0000</frequency>
						<q>1.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a10">
			<presetlabel>Cardiac Output - dZ/dt</presetlabel>
			<channellabel>Cardiac Output - dZ/dt</channellabel>
			<unitslabel>Ohms/sec</unitslabel>
			<scaling>
				<value unscaled="0.000000000000000" scaled="0.000000000000000" />
				<value unscaled="0.005000000000000" scaled="2.000000000000000" />
			</scaling>
			<hardwareconfig type="35">
				<settings>
					<gain>200</gain>
					<offset>0.0000</offset>
					<inputcoupling>DC</inputcoupling>
					<highpassfilter>0.5</highpassfilter>
				</settings>
				<dspfiltercollection>
					<dspfilter type="LowPass">
						<frequency>66.5000</frequency>
						<q>0.5000</q>
					</dspfilter>
					<dspfilter type="LowPass">
						<frequency>38.5000</frequency>
						<q>1.0000</q>
					</dspfilter>
					<dspfilter type="BandStopLineFrequency">
						<frequency>60.0000</frequency>
						<q>1.0000</q>
					</dspfilter>
				</dspfiltercollection>
			</hardwareconfig>
		</analogpreset>
		<analogpreset uid="a11">
			<presetlabel>Clench Force (kg)</presetlabel>
			<channellabel>Clench Force</channellabel>
			<unitslabel>kg</unitslabel>
			<scaling>
